import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export const metadata = {
  title: "FAQ | Velocine",
  description: "Frequently Asked Questions about Velocine Studio.",
};

const faqs = [
  {
    question: "Do I need to know how to edit videos?",
    answer: "Not at all. Velocine is designed for creators of all experience levels. You upload your long-form video, and our AI automatically analyzes the content, detects the best hooks, and generates styled short-form clips you can post immediately.",
  },
  {
    question: "What platforms are the clips optimized for?",
    answer: "Our engine produces vertical (9:16) clips that are perfectly optimized for TikTok, Instagram Reels, YouTube Shorts, and Facebook Reels. We handle the framing and captioning so they look native everywhere.",
  },
  {
    question: "How long can my source videos be?",
    answer: "Depending on your plan, you can upload videos ranging from 30 minutes up to 3 hours. Velocine processes them incredibly fast, usually delivering your clips in just a few minutes.",
  },
  {
    question: "Can I customize the captions and styling?",
    answer: "Yes. While our AI picks the most engaging styles by default (like the Alex Hormozi or Ali Abdaal styles), you have full control in the Studio dashboard to tweak colors, fonts, and caption animations to match your brand.",
  },
  {
    question: "Do I retain ownership of the content?",
    answer: "Absolutely. You own 100% of the content you upload and the clips generated by Velocine. We don't claim any rights over your videos.",
  },
];

export default function FAQPage() {
  return (
    <div className="flex flex-col w-full min-h-screen pt-24 pb-32 bg-background">
      <div className="container px-4 md:px-6 max-w-4xl mx-auto flex flex-col items-center">
        {/* Header */}
        <div className="text-center space-y-4 mb-16">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight">
            Frequently Asked Questions
          </h1>
          <p className="text-xl text-muted-foreground">
            Everything you need to know about scaling your content with Velocine.
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="w-full bg-card/40 border border-border/50 rounded-2xl p-6 md:p-10 backdrop-blur-md shadow-2xl">
          <Accordion type="single" collapsible className="w-full space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem 
                key={index} 
                value={`item-${index}`} 
                className="border border-white/10 rounded-xl px-6 bg-black/20 hover:bg-black/40 transition-colors"
              >
                <AccordionTrigger className="text-left text-lg font-medium py-6 hover:no-underline hover:text-orange-400 transition-colors">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-zinc-400 text-base leading-relaxed pb-6">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>

        {/* Bottom CTA */}
        <div className="mt-24 text-center space-y-6">
          <h2 className="text-2xl md:text-3xl font-bold">Still have questions?</h2>
          <p className="text-muted-foreground max-w-lg mx-auto">
            Our support team is ready to help you optimize your content workflow. Reach out anytime.
          </p>
          <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="mailto:support@velocine.app">
              <Button size="lg" variant="outline" className="h-12 px-8 rounded-full">
                Contact Support
              </Button>
            </Link>
            <Link href="https://studio.velocine.app/signup">
              <Button size="lg" className="h-12 px-8 rounded-full bg-orange-500 hover:bg-orange-600 text-white">
                Try Velocine Free
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
